version: '3'
services:
  app:
    container_name: app
    build: .
    tty: true
    # environment:
    #   APP_MODE: local
    #   DB_PASSWORD: localpass
    # volumes:
    #   - './src:/go/src/chat_app'
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5430:5432'
    volumes:
      - ./postgres:/var/lib/postgresql
      - ./postgres-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatapp_db
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    restart: always
    tty: true

  proxy:
    container_name: proxy
    build: ./nginx
    ports:
      - '8081:80'
    depends_on:
      - app
