version: '3'
services:
  app:
    build: .
    tty: true
    environment:
      APP_MODE: local
      DB_PASSWORD: localpass
    volumes:
      - './:/go/src/app'
    depends_on:
      - db

  db:
    image: postgres:13.4
    ports:
      - 5431:5431
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatapp_db
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'

  proxy:
    build: ./nginx
    ports:
      - '8081:80'
    depends_on:
      - app
