version: '3.5'

services:
  app:
    # build: .
    image: golang:latest
    tty: true
    # environment:
    #   APP_MODE: local
    #   DB_PASSWORD: localpass
    volumes:
      - './app:/go/src/chat_app'
    depends_on:
      - db

  db:
    # build:
    # context: database
    image: postgres:latest
    volumes:
      - ./postgres:/var/lib/postgresql
      - ./postgres-init:/docker-entrypoint-initdb.d
    # expose:
    #   - '5432'
    ports:
      - '5430:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    restart: 'always'

  proxy:
    image: nginx:latest
    ports:
      - '8088:80'
#     networks:
#       - db-net

# networks:
#   db-net:
#     driver: bridge
